# coding: utf-8

# flake8: noqa

"""
    Event Management System

    This YAML doc depicts the various endpoints to a RESTapi for a Event management system  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.event_api import EventApi
from swagger_client.api.user_api import UserApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.api_response import ApiResponse
from swagger_client.models.event import Event
from swagger_client.models.user import User
