# coding: utf-8

"""
    Event Management System

    This YAML doc depicts the various endpoints to a RESTapi for a Event management system  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.event_api import EventApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEventApi(unittest.TestCase):
    """EventApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.event_api.EventApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_event(self):
        """Test case for add_event

        Add a new event  # noqa: E501
        """
        pass

    def test_api_event_event_id_put(self):
        """Test case for api_event_event_id_put

        Edit event by ID  # noqa: E501
        """
        pass

    def test_getevent_by_id(self):
        """Test case for getevent_by_id

        Find event by ID  # noqa: E501
        """
        pass

    def test_remove_event(self):
        """Test case for remove_event

        Delete event  # noqa: E501
        """
        pass

    def test_update_pet(self):
        """Test case for update_pet

        Update an existing pet  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
