"""empty message

Revision ID: 6a511fd42404
Revises: f4b89099f838
Create Date: 2021-08-05 09:35:22.278851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a511fd42404'
down_revision = 'f4b89099f838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Affiliate_ibfk_1', 'Affiliate', type_='foreignkey')
    op.drop_constraint('Affiliate_ibfk_2', 'Affiliate', type_='foreignkey')
    op.create_foreign_key(None, 'Affiliate', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Affiliate', 'Group', ['groupId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Group_ibfk_1', 'Group', type_='foreignkey')
    op.create_foreign_key(None, 'Group', 'User', ['admin'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Schedule_ibfk_1', 'Schedule', type_='foreignkey')
    op.drop_constraint('Schedule_ibfk_2', 'Schedule', type_='foreignkey')
    op.create_foreign_key(None, 'Schedule', 'Event', ['eventId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Schedule', 'Group', ['groupId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Submit_ibfk_2', 'Submit', type_='foreignkey')
    op.drop_constraint('Submit_ibfk_1', 'Submit', type_='foreignkey')
    op.create_foreign_key(None, 'Submit', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Submit', 'Event', ['eventId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Submit', type_='foreignkey')
    op.drop_constraint(None, 'Submit', type_='foreignkey')
    op.create_foreign_key('Submit_ibfk_1', 'Submit', 'Event', ['eventId'], ['id'])
    op.create_foreign_key('Submit_ibfk_2', 'Submit', 'User', ['userId'], ['id'])
    op.drop_constraint(None, 'Schedule', type_='foreignkey')
    op.drop_constraint(None, 'Schedule', type_='foreignkey')
    op.create_foreign_key('Schedule_ibfk_2', 'Schedule', 'Group', ['groupId'], ['id'])
    op.create_foreign_key('Schedule_ibfk_1', 'Schedule', 'Event', ['eventId'], ['id'])
    op.drop_constraint(None, 'Group', type_='foreignkey')
    op.create_foreign_key('Group_ibfk_1', 'Group', 'User', ['admin'], ['id'])
    op.drop_constraint(None, 'Affiliate', type_='foreignkey')
    op.drop_constraint(None, 'Affiliate', type_='foreignkey')
    op.create_foreign_key('Affiliate_ibfk_2', 'Affiliate', 'User', ['userId'], ['id'])
    op.create_foreign_key('Affiliate_ibfk_1', 'Affiliate', 'Group', ['groupId'], ['id'])
    # ### end Alembic commands ###
