"""empty message

Revision ID: 71c23a6dfd0c
Revises: 
Create Date: 2021-08-04 12:33:01.542447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c23a6dfd0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=1024), nullable=True),
    sa.Column('last_name', sa.String(length=1024), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Affiliate',
    sa.Column('userId', sa.String(length=1024), nullable=False),
    sa.Column('groupId', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['groupId'], ['Group.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('userId', 'groupId')
    )
    op.create_table('Schedule',
    sa.Column('eventId', sa.String(length=1024), nullable=False),
    sa.Column('groupId', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['Event.id'], ),
    sa.ForeignKeyConstraint(['groupId'], ['Group.id'], ),
    sa.PrimaryKeyConstraint('eventId', 'groupId')
    )
    op.create_table('Submit',
    sa.Column('eventId', sa.String(length=1024), nullable=False),
    sa.Column('userId', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['Event.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('eventId', 'userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Submit')
    op.drop_table('Schedule')
    op.drop_table('Affiliate')
    op.drop_table('Group')
    op.drop_table('Event')
    op.drop_table('User')
    # ### end Alembic commands ###
